name: ai_infra_monitor
version: "1.0.0"
config-version: 2

profile: ai_infra_monitor

model-paths:  ["models"]
seed-paths:   ["seeds"]
macro-paths:  ["macros"]
test-paths:   ["tests"]

target-path:  "target"
clean-targets: ["target", "dbt_packages"]

models:
  ai_infra_monitor:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
